export const mockRooms = [
  {
    id: '1',
    name: 'Dorm A',
    type: 'dormitory',
    beds: 8,
    occupiedBeds: 6,
  },
  {
    id: '2',
    name: 'Dorm B',
    type: 'dormitory',
    beds: 6,
    occupiedBeds: 6,
  },
  {
    id: '3',
    name: 'Private Room 1',
    type: 'private',
    beds: 2,
    occupiedBeds: 0,
  },
  {
    id: '4',
    name: 'Private Room 2',
    type: 'private',
    beds: 2,
    occupiedBeds: 1,
  },
  {
    id: '5',
    name: 'Suite',
    type: 'suite',
    beds: 4,
    occupiedBeds: 0,
  },
]

export const mockBookings = [
  {
    id: '1',
    guestName: 'John Smith',
    roomName: 'Dorm A',
    checkIn: '2024-12-10',
    checkOut: '2024-12-15',
    status: 'confirmed',
  },
  {
    id: '2',
    guestName: 'Maria Garcia',
    roomName: 'Dorm A',
    checkIn: '2024-12-10',
    checkOut: '2024-12-12',
    status: 'checked_in',
  },
  {
    id: '3',
    guestName: 'David Lee',
    roomName: 'Private Room 2',
    checkIn: '2024-12-11',
    checkOut: '2024-12-14',
    status: 'confirmed',
  },
  {
    id: '4',
    guestName: 'Sarah Johnson',
    roomName: 'Dorm B',
    checkIn: '2024-12-12',
    checkOut: '2024-12-18',
    status: 'pending',
  },
  {
    id: '5',
    guestName: 'Ahmed Hassan',
    roomName: 'Dorm A',
    checkIn: '2024-12-15',
    checkOut: '2024-12-20',
    status: 'confirmed',
  },
]
