#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run integration tests before pushing
npm run test:ci

# Check test coverage threshold
npx jest --coverage --coverageThreshold='{"global":{"branches":80,"functions":80,"lines":80,"statements":80}}'